import CustomCursor from "@/components/CustomCursor/CustomCursor";
import "./globals.css";
import { Inter, Raleway } from "next/font/google";
import SideNavbar from "@/components/SideNavbar/SideNavbar";
import { ThemeProvider } from "./ThemeProvider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({
  subsets: ["latin-ext"],
  display: "swap",
  strategy: "selfHosted",
});
export const metadata = {
  title: "NextFolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined&display=optional"
        />
      </head>

      <body className={`${inter.className} flex flex-row items-start`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
          <CustomCursor />
          <SideNavbar />
          <main
            className={`${inter.className} pl-8 md:pl-16 pb-16 w-full h-screen overflow-y-auto dark:bg-dark dark:text-white transition-all duration-300 ease-in-out`}
          >
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
